#!/usr/bin/env bash

# This is an auomated script to install archlinux minimal (dual boot MS-Windows).
# Internal use

part_one(){
	# Set latinamrican keyboard.
	loadkeys la-latin1
	## Check internet connection.
	internet=$(ping archlinux.org -c1 | grep -wo "1 packets")
	if [[ -n $internet ]] ; then
		clear
		echo -e "Internet connection working :)\n"
		sleep 0.5
	else
		wifi-menu
	fi
	# Update system clock
	timedatectl set-ntp true
	# Install a bigger font
	pacman -Sy terminus-font --noconfirm
	setfont ter-v20b
	## Sort servers rank for speed
	pacman -Sy pacman-rankmirros --noconfirm
	pacman -Sy pacman-contrib --noconfirm
	rm -f /etc/pacman.d/mirrorlist --noconfirm
	# Get the mirrorlist directly from the website.
	curl -o /etc/pacman.d/mirrorlist https://www.archlinux.org/mirrorlist/all/
	cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.back
	sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.back
	nohup rankmirrors -n 6 /etc/pacman.d/mirrorlist.back > /etc/pacman.d/mirrorlist &
	pid=$!
	cgdisk /dev/sda
	mkfs.ext4 /dev/sda5 -L "Archlinux"
	mkswap /dev/sda6 -L "Swap"
	mkdir /mnt/boot
	mount /dev/sda5 /mnt
	mount /dev/sda2 /mnt/boot
	swapon /dev/sda6
	wait $pid
	pacstrap /mnt base base-devel
	genfstab -U /mnt >> /mnt/etc/fstab
	clear ; echo "Ctrl+C if something was wrong" ; sleep 10
	arch-chroot /mnt
}
part_two(){
	# Time zone
	ln -sf /usr/share/zoneinfo/America/Mexico_city /etc/localtime
	hwclock --systohc
	sed -i 's/^#en_US.UTF-8/en_US.UTF-8/'  /etc/locale.gen
	sed -i 's/^#es_MX.UTF-8/es_MX.UTF-8/'  /etc/locale.gen
	locale-gen
	echo "LANG=en_US.UTF-8" > /etc/locale.conf
	echo -e  "KEYMAP=la-latin1\nFONT=ter-v20b" > /etc/vconsole.conf
	clear
	read -p "Ingresa el nombre del equipo: " hostNAME
	echo "$hostNAME" > /etc/hostname
	rm -f /etc/hosts
	echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t${hostNAME}.localdomain\t$hostNAME" > /etc/hosts
	mkinitcpio -p linux
	bootctl install
	clear
	echo "Enter the root password"
	passwd
	rm -f /boot/loader/loader.conf
	echo -e "default\tarch\ntimeout\t5" > /boot/loader/loader.conf
	uuid=$(blkid | grep /dev/sda5 | awk {'print $3'} | sed -e 's/"//g')
	echo -e "title GNU/Linux Archlinux D@nNix main OS\nlinux /vmlinuz-linux\ninitrd /intel-ucode.img\ninitrd /initramfs-linux.img\noptions root=$uuid rw" > /boot/loader/entries/arch.conf
	pacman -Sy intel-ucode iw wpa_supplicant networkmanager dialog terminus-font git wget openssh --noconfirm
}

quit(){
	clear
	exit 0
}

main(){
	clear
	echo -e "1) First config\n2) Inside the new sys"
	read -p "ingresa una opción: " opt
	case $opt in
		1)	part_one ;;
		2)	part_two ;;
		3)	quit	 ;;
		*) 	echo "opcion no valida" ;;
	esac
}
main
