#!/usr/bin/env bash

# This is an auomated script to install archlinux minimal.
# Personal use.	

part_cero(){
	pacman -Sy git
	git clone https://github.com/dannyMendoza/arch_auto_install
	git config --global user.email 'daniel.mendoza@alumnos.udg.mx'
	git config --global user.name 'dannyMendoza'
}

part_one(){
	# Set latinamrican keyboard.
	loadkeys la-latin1
	## Check internet connection.
	internet=$(ping -c1 archlinux.org | grep -wo "1 packets")
	if [[ -n $internet ]] ; then
		clear
		echo -e "Internet connection working :)\n"
		sleep 0.5
	else
		echo -e "Internet conection does not work :(\n"
		wifi-menu
	fi
	# Update system clock
	timedatectl set-ntp true
	# Install a bigger font
	pacman -Sy terminus-font --noconfirm
	setfont ter-v32b
	## Sort servers rank for speed
	pacman -Sy pacman-mirrorlist --noconfirm
	pacman -Sy pacman-contrib --noconfirm
	rm -f /etc/pacman.d/mirrorlist
	# Get the mirrorlist directly from the website.
	curl -o /etc/pacman.d/mirrorlist https://www.archlinux.org/mirrorlist/all/
	cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.back
	sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.back
	rankmirrors -n 6 /etc/pacman.d/mirrorlist.back > /etc/pacman.d/mirrorlist &
	pid=$!
	## Partioning
	parted --script /dev/sda \
		mklabel gpt \
		mkpart primary fat32 1MiB 513MiB \
		mkpart primary ext4 513MiB 100% \
		set 1 esp on \
		set 2 lvm on
	cryptsetup luksFormat /dev/sda2
	cryptsetup open /dev/sda2 cryptlvm
	pvcreate /dev/mapper/cryptlvm
	vgcreate archlvm /dev/mapper/cryptlvm
	lvcreate -L 280G archlvm -n cryptroot_lvm
	lvcreate -L 8G archlvm -n cryptswap_lvm
	lvcreate -l 100%FREE archlvm -n crypthome_lvm
	# encrypt root partition
	mkfs.vfat -F32 /dev/sdb1 -n "EFIBOOT"
	mkfs.ext4 /dev/archlvm/cryptroot_lvm -L "root_arch"
	mkfs.ext4 /dev/archlvm/crypthome_lvm -L "home_arch"
	mkswap /dev/archlvm/cryptswap_lvm -L "swap_arch"
	mount /dev/archlvm/cryptroot_lvm /mnt
	mkdir /mnt/{boot,home}
	mount /dev/sda1 /mnt/boot
	mount /dev/archlvm/crypthome_lvm /mnt/home
	swapon /dev/archlvm/cryptswap_lvm
	wait $pid
	pacstrap /mnt base base-devel linux linux-firmware vim
	genfstab -p -U /mnt >> /mnt/etc/fstab
	cp AutoInstall /mnt/home
	echo -e "\n\nCtrl+C if something was wrong" ; sleep 10
	arch-chroot /mnt
}
part_two(){
	# Time zone
	pacman -Sy vim intel-ucode iw wpa_supplicant networkmanager dialog terminus-font git wget openssh zsh zsh-completions zsh-syntax-highlighting zsh-autosuggestions --noconfirm
	ln -sf /usr/share/zoneinfo/America/Mexico_city /etc/localtime
	hwclock --systohc
	sed -i 's/^#en_US/en_US/'  /etc/locale.gen
	sed -i 's/^#es_MX/es_MX/'  /etc/locale.gen
	locale-gen
	echo "LANG=en_US.UTF-8" > /etc/locale.conf
	echo -e  "KEYMAP=la-latin1\nFONT=ter-v16b" > /etc/vconsole.conf
	clear
	read -p "Ingresa el nombre del equipo: " hostNAME
	echo "$hostNAME" > /etc/hostname
	rm -f /etc/hosts
	echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t${hostNAME}.localdomain\t$hostNAME" > /etc/hosts
	echo -e "\n### Edit the file and insert lvm2 between block and filesystems" >> /etc/mkinitcpio.conf
	echo -e "### HOOKS=(base udev autodetect keyboard keymap consolefont modconf block lvm2 encrypt filesystems fsck)" >> /etc/mkinitcpio.conf
	vim /etc/mkinitcpio.conf
	mkinitcpio -p linux
	bootctl install
	clear
	echo "Enter the root password"
	passwd
	rm -f /boot/loader/loader.conf
	echo -e "default\tarch\ntimeout\t5" > /boot/loader/loader.conf
	uuid=$(blkid | grep /dev/sda2 | awk {'print $2'} | sed -e 's/"//g')
	echo -e "title GNU/Linux Arch linux D@nNix\nlinux /vmlinuz-linux\ninitrd /intel-ucode.img\ninitrd /initramfs-linux.img\noptions cryptdevice=${uuid}:cryptlvm root=/dev/archlvm/cryptroot_lvm rw" > /boot/loader/entries/arch.conf
}

quit(){
	clear
	exit 0
}

main(){
	clear
	echo -e "1) First config\n2) Inside the new sys"
	read -p "ingresa una opción: " opt
	case $opt in
		1)	part_one ;;
		2)	part_two ;;
		3)	quit	 ;;
		*) 	echo "opcion no valida" ;;
	esac
}
main
